### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by ythecombinator** [getstalkr/getstalkr.github.io#1]
### Explored Topics 

- [X] What
- [X] Current Packages
- [X] Our team
- [X] Sign up for Beta

#### PWA

- [ ] Offline Caching (via [Service Worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API)s)

- [ ] Cache Busting

- [ ] Good page loading metrics (audited by tools like *LIGHTHOUSE*, *WebPageTest*, *PageSpeed Insights* etc.)

- [ ] Secure network connection

- [ ] User can be prompted to `Add to Homescreen`

- [ ] Installed web app will launch with custom splash screen

- [ ] Mobile-friendly design

#### Tooling

- [ ] `ES2015` & `ES2016` support (maybe with a *compile-to-JS* language; eg. [TypeScript](https://www.typescriptlang.org/))

- [ ] Webpack Bundle Analysis

- [ ] Hot Module Replacement (HMR)

- [ ] [Preact](https://github.com/developit/preact), [next.js](https://github.com/zeit/next.js/) or other big players–for experimenting purposes
